
// This file has been generated by the GUI designer. Do not modify.
namespace CmisSync.Widgets
{
	public partial class ProxyWidget
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.RadioButton noProxyButton;
		private global::Gtk.RadioButton systemProxyButton;
		private global::Gtk.RadioButton customProxyButton;
		private global::CmisSync.Widgets.UrlWidget urlwidget3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CmisSync.Widgets.ProxyWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CmisSync.Widgets.ProxyWidget";
			// Container child CmisSync.Widgets.ProxyWidget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.noProxyButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("No Proxy"));
			this.noProxyButton.CanFocus = true;
			this.noProxyButton.Name = "noProxyButton";
			this.noProxyButton.DrawIndicator = true;
			this.noProxyButton.UseUnderline = true;
			this.noProxyButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox3.Add (this.noProxyButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.noProxyButton]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.systemProxyButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("System Default Proxy"));
			this.systemProxyButton.CanFocus = true;
			this.systemProxyButton.Name = "systemProxyButton";
			this.systemProxyButton.DrawIndicator = true;
			this.systemProxyButton.UseUnderline = true;
			this.systemProxyButton.Group = this.noProxyButton.Group;
			this.vbox3.Add (this.systemProxyButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.systemProxyButton]));
			w2.Position = 1;
			w2.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.customProxyButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Custom Proxy"));
			this.customProxyButton.CanFocus = true;
			this.customProxyButton.Name = "customProxyButton";
			this.customProxyButton.DrawIndicator = true;
			this.customProxyButton.UseUnderline = true;
			this.customProxyButton.Group = this.noProxyButton.Group;
			this.vbox3.Add (this.customProxyButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.customProxyButton]));
			w3.Position = 2;
			w3.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.urlwidget3 = new global::CmisSync.Widgets.UrlWidget ();
			this.urlwidget3.Events = ((global::Gdk.EventMask)(256));
			this.urlwidget3.Name = "urlwidget3";
			this.urlwidget3.IsUrlEditable = false;
			this.urlwidget3.ValidationActivated = false;
			this.vbox3.Add (this.urlwidget3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.urlwidget3]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 4;
			w4.Expand = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
