
// This file has been generated by the GUI designer. Do not modify.
namespace CmisSync
{
	public partial class Setting
	{
		private global::Gtk.VBox vbox5;
		private global::Gtk.Notebook tabs;
		private global::CmisSync.Widgets.ProxyWidget proxyWidget;
		private global::Gtk.Label label1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.CheckButton notificationToggleButton;
		private global::Gtk.Label label2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label3;
		private global::Gtk.Button saveButton;
		private global::Gtk.Button cancelButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CmisSync.Setting
			this.Name = "CmisSync.Setting";
			this.Title = global::Mono.Unix.Catalog.GetString ("Setting");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(3));
			// Container child CmisSync.Setting.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.tabs = new global::Gtk.Notebook ();
			this.tabs.CanFocus = true;
			this.tabs.Name = "tabs";
			this.tabs.CurrentPage = 1;
			// Container child tabs.Gtk.Notebook+NotebookChild
			this.proxyWidget = new global::CmisSync.Widgets.ProxyWidget ();
			this.proxyWidget.Events = ((global::Gdk.EventMask)(256));
			this.proxyWidget.Name = "proxyWidget";
			this.tabs.Add (this.proxyWidget);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.tabs.SetTabLabel (this.proxyWidget, this.label1);
			this.label1.ShowAll ();
			// Container child tabs.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notificationToggleButton = new global::Gtk.CheckButton ();
			this.notificationToggleButton.CanFocus = true;
			this.notificationToggleButton.Name = "notificationToggleButton";
			this.notificationToggleButton.Label = global::Mono.Unix.Catalog.GetString ("Notifications");
			this.notificationToggleButton.DrawIndicator = true;
			this.notificationToggleButton.UseUnderline = true;
			this.vbox1.Add (this.notificationToggleButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notificationToggleButton]));
			w2.Position = 0;
			w2.Expand = false;
			this.tabs.Add (this.vbox1);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.tabs [this.vbox1]));
			w3.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
			this.tabs.SetTabLabel (this.vbox1, this.label2);
			this.label2.ShowAll ();
			this.vbox5.Add (this.tabs);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.tabs]));
			w4.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w5.Position = 0;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.saveButton = new global::Gtk.Button ();
			this.saveButton.CanFocus = true;
			this.saveButton.Name = "saveButton";
			this.saveButton.UseUnderline = true;
			this.saveButton.Label = global::Mono.Unix.Catalog.GetString ("Save changes");
			this.hbox2.Add (this.saveButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.saveButton]));
			w6.Position = 1;
			w6.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseUnderline = true;
			this.cancelButton.Label = global::Mono.Unix.Catalog.GetString ("Discard Changes");
			this.hbox2.Add (this.cancelButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cancelButton]));
			w7.Position = 2;
			w7.Expand = false;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 402;
			this.DefaultHeight = 323;
			this.Hide ();
			this.notificationToggleButton.Toggled += new global::System.EventHandler (this.OnNotificationToggleButtonToggled);
		}
	}
}
