
// This file has been generated by the GUI designer. Do not modify.
namespace CmisSync.Widgets
{
	public partial class BandwidthSettingsWidget
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::CmisSync.Widgets.BandwidthLimitWidget uploadLimitWidget;
		
		private global::Gtk.Label uploadLabel;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::CmisSync.Widgets.BandwidthLimitWidget downloadLimitWidget;
		
		private global::Gtk.Label downloadLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CmisSync.Widgets.BandwidthSettingsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CmisSync.Widgets.BandwidthSettingsWidget";
			// Container child CmisSync.Widgets.BandwidthSettingsWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.uploadLimitWidget = new global::CmisSync.Widgets.BandwidthLimitWidget ();
			this.uploadLimitWidget.Events = ((global::Gdk.EventMask)(256));
			this.uploadLimitWidget.Name = "uploadLimitWidget";
			this.uploadLimitWidget.Limit = 0;
			this.GtkAlignment.Add (this.uploadLimitWidget);
			this.frame1.Add (this.GtkAlignment);
			this.uploadLabel = new global::Gtk.Label ();
			this.uploadLabel.Name = "uploadLabel";
			this.uploadLabel.Xalign = 0F;
			this.uploadLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Upload Limit</b>");
			this.uploadLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.uploadLabel;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.downloadLimitWidget = new global::CmisSync.Widgets.BandwidthLimitWidget ();
			this.downloadLimitWidget.Events = ((global::Gdk.EventMask)(256));
			this.downloadLimitWidget.Name = "downloadLimitWidget";
			this.downloadLimitWidget.Limit = 0;
			this.GtkAlignment1.Add (this.downloadLimitWidget);
			this.frame2.Add (this.GtkAlignment1);
			this.downloadLabel = new global::Gtk.Label ();
			this.downloadLabel.Name = "downloadLabel";
			this.downloadLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Download Limit</b>");
			this.downloadLabel.UseMarkup = true;
			this.frame2.LabelWidget = this.downloadLabel;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
