
// This file has been generated by the GUI designer. Do not modify.
namespace CmisSync
{
	public partial class TransmissionWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.VBox transmissionList;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CmisSync.TransmissionWindow
			this.Name = "CmisSync.TransmissionWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TransmissionWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child CmisSync.TransmissionWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.transmissionList = new global::Gtk.VBox ();
			this.transmissionList.Name = "transmissionList";
			w1.Add (this.transmissionList);
			this.GtkScrolledWindow.Add (w1);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 542;
			this.DefaultHeight = 324;
			this.Show ();
		}
	}
}
